### ISSUE TITLE
Support command "GETDEL"

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/RedisLess#18]
Let's support Redis command "[GETDEL](https://redis.io/commands/getdel)"

**Comment by clarity0** [comment]
The Redis crate doesn't implement getdel on its client, so can't test it easily with that

**Comment by evoxmusic** [comment]
> The Redis crate doesn't implement getdel on its client, so can't test it easily with that

https://github.com/Qovery/RedisLess/blob/main/redisless/src/server.rs#L382

Maybe this way will work?
