### ISSUE TITLE
Support command "GETSET"

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/RedisLess#19]
Let's support Redis command "[GETSET](https://redis.io/commands/getset)"

**Comment by clarity0** [comment]
Is the reason for the timeouts on the start and stop server multiple times something to do with the ports?

**Comment by evoxmusic** [comment]
> Is the reason for the timeouts on the start and stop server multiple times test something to do with the ports?

Yes, that's why we are maybe better to randomize the listening port for tests.
