### ISSUE TITLE
Support command "INCRBY"

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/RedisLess#3]
Let's support "[INCRBY](https://redis.io/commands/incrby)" Redis command.

**Comment by pepoviola** [comment]
Hi @evoxmusic, I can take this one if no one else is working on.
Thx!

**Comment by evoxmusic** [comment]
Sure, you're welcome @pepoviola :)

**Comment by pepoviola** [comment]
Implemented in https://github.com/Qovery/RedisLess/pull/30
