### ISSUE TITLE
Separate big modules into smaller submodules

### ISSUE THREAD

**Issue by clarity0** [Qovery/RedisLess#36]
Files are too long maybe, what do you think?

**Comment by evoxmusic** [comment]
That's good idea - but maybe it is too soon? What structure would you suggest?

**Comment by clarity0** [comment]
Something like this?
```
src
|--------protocol
| 	|--------mod.rs
|	|--------error
|		|--------mod.rs
|		|--------redis_error.rs
|		|--------command_error.rs
|--------command
|	|--------mod.rs
|	|--------util.rs
|--------server
	|--------mod.rs
	|--------util
		|--------mod.rs
		|--------each util function
		|--------here in its own file
```

**Comment by evoxmusic** [comment]
It looks good for me - being consistent is the most important at our stage. What do you think @pjeziorowski?

**Note to consider**: I am working on a branch where I have modified a bit the structure as well. Maybe we are better to change all of that once I merged it into the main one?

The branch is to support the "[cluster mode](https://github.com/Qovery/RedisLess/tree/feat/cluster_mode)"
