### ISSUE TITLE
Use a Response enum

### ISSUE THREAD

**Issue by clarity0** [Qovery/RedisLess#41]
Currently every response is formatted independently
I think it would be better to implement a struct to do this.

**Comment by evoxmusic** [comment]
What do you mean by a "responder struct"?

**Comment by clarity0** [comment]
```rust

pub enum RedisResponse {
    Integer(u32),
    SimpleString(String),
    BulkString(String),
    Array(Vec<RedisResponse>),
}

impl RedisResponse {
    fn respond(&self) -> Vec<u8>{
        match data {
            ...
        }
    }
}

```
This way no matter what the response type is, the handling of the formatting of the response delegated to the Respond function and away from the logic of the other commands.

**Comment by evoxmusic** [comment]
I agree with that. It will be clearer for everyone

**Comment by clarity0** [comment]
#47
